# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23996ebe8db2ed9864e83d89fe43bb9792c74a94bc19278da3fa967157629d2e22f303d26c84a611b1230f8bfd7eb13f0d24166a61ba67b887500ec391a44598

test:
  secret_key_base: 99f3225a91c89d93f923416d808b494e7098f1289ec1aab88c0be4df22b1e27a4d8211c5e5ad97d09a9bf3d0c74c7291e88b8ec370219046ff0382e7b5b5b3a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
